language: generic
env:
    global:
        # full path to Saxon jar
        - SAXON_CP=/tmp/schematron/saxon/saxon9he.jar
        # full path to XML Resolver jar
        - XML_RESOLVER_CP=/tmp/schematron/xml-resolver/resolver.jar
        - SCHEMATRON_XSLT_INCLUDE=$PWD/trunk/schematron/code/iso_dsdl_include.xsl
        - SCHEMATRON_XSLT_EXPAND=$PWD/trunk/schematron/code/iso_abstract_expand.xsl
        - SCHEMATRON_XSLT_COMPILE=$PWD/trunk/schematron/code/iso_svrl_for_xslt2.xsl
        - XSPEC_HOME=$PWD/trunk/schematron/test/xspec-dist
    matrix:
        # latest Saxon 9.8 version and full path to Jing jar
        - SAXON_VERSION=9.8.0-7
          JING_CP=/tmp/schematron/jing/jing.jar

before_install:
    - unset _JAVA_OPTIONS

before_script:
    # install Saxon
    - curl -fsSL --create-dirs -o ${SAXON_CP} http://central.maven.org/maven2/net/sf/saxon/Saxon-HE/${SAXON_VERSION}/Saxon-HE-${SAXON_VERSION}.jar
    # install XML Resolver
    - curl -fsSL --create-dirs -o ${XML_RESOLVER_CP} http://central.maven.org/maven2/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar

script:
    - cd trunk/schematron/test
    - echo "execute bats unit tests"
    - bats --tap schematron.bats
